
package views;

public class Form extends javax.swing.JFrame {

    public Form() {
        initComponents();
        this.setResizable(false);
        this.setSize(740, 400);
        this.setLocation(500, 300);
        this.setTitle("Registro de empleados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPosition = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        txtLastname = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmployeesList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(37, 40, 61));

        jPanel1.setBackground(new java.awt.Color(37, 40, 61));
        jPanel1.setLayout(null);

        txtPosition.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));
        jPanel1.add(txtPosition);
        txtPosition.setBounds(20, 220, 250, 50);

        btnMostrar.setBackground(new java.awt.Color(143, 57, 133));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar);
        btnMostrar.setBounds(150, 290, 120, 40);

        btnRegister.setBackground(new java.awt.Color(143, 57, 133));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(20, 290, 120, 40);

        txtLastname.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        jPanel1.add(txtLastname);
        txtLastname.setBounds(20, 80, 250, 50);

        txtSalary.setBorder(javax.swing.BorderFactory.createTitledBorder("Salario"));
        jPanel1.add(txtSalary);
        txtSalary.setBounds(20, 150, 250, 50);

        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName);
        txtName.setBounds(20, 10, 250, 50);

        txtEmployeesList.setColumns(20);
        txtEmployeesList.setRows(5);
        txtEmployeesList.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de empleados"));
        jScrollPane1.setViewportView(txtEmployeesList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 10, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMostrar;
    public javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtEmployeesList;
    public javax.swing.JTextField txtLastname;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPosition;
    public javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

}
